extends Node

signal progress_scene(scene : String)
signal add_to_score(number: int)
signal update_score()
signal update_distance(distance: int)
signal submit_max_distance(new_distance: int)
signal update_player_flags()
signal repulse_blackhole()
signal restart_game()
signal remove_keybind(action,event)
signal create_keybind()
signal update_repulser_label(count: int)
signal fade_to_scene(scene: String)
signal player_escape()
